### PR TITLE
fix some github issues

### LINKED ISSUE #305: alert :the query was executed at an incorrect time
` WHERE $timeFilter AND $to -$from<3601`
This is my query.When I use Alert, I test that the values from and to are correct.But the rawQuery value is problematic.

logs[0].data : 
`from:1605667726607`
`to:1605667846607`
`WHERE  timestamp >= toDateTime(1605667340) AND 1605667640 -1605667340<3601`
You can see that the values from and to are not used. I think the value of from and to is correct.But rawQuery USES window time

My alert :
condition:  query(A, 2m, now)

ps:
At first I used it directly, but a few days later I noticed that there were some slow queries in the SQL, and the time seemed to be used instead of the alert execution time.

### LINKED ISSUE #327: RawQuery cause time condition using from / to useless
When using alert with clickhouse-grafana , time was immutable when using from / to  as #305 metioned

After digging into source code for both grafana & clickhouse-grafana
I found it was a problem with rawQuery 

Everytime you edit the panel query then save, a rawQuery field in panel.targets **and also in alertRuleTags.query** was generated
rawQuery was transformed in sql_query.ts, the logic replaced all paramters to determine value
So rawQuery will hold the variable value when dashboard was saved

It's no problem when viewing dashboard in browser,but in alerting,things changed
Alerting loads rule from database,then sends to clickhouse-grafana plugin
the transform logic has no change to trigger,Then cause the from / to unchanged problem

Suggest move the logic from sql_query.ts to datasource.go,and use formattedQuery as query template

### LINKED ISSUE #328: Grafana 7.4.2 Variables query using clickhouse groupArray() dosn't working
Duplicate issue from https://github.com/grafana/grafana/issues/31445
In grafana variables 7.4.x, an error occurs when using the groupArray () function in a request. 
In versions 7.3.x everything works fine.

### PR DESCRIPTION
**Pull request by Slach**
The issue with array in variables on grafana side is reproducible
close #328 

partial fix for alerts for use case when query evaluates on server-side each time with same time range,
close #327 
close #305

### CODE REVIEW

File: pkg/query.go [hunk 1]
```diff
@@ -12,17 +15,41 @@ var DefaultQuery = "SELECT 1 FORMAT JSON;"
 var TimeZoneFieldName = "timezone()"
 var TimeZoneQuery = fmt.Sprintf("SELECT %s FORMAT JSON;", TimeZoneFieldName)
 
+/* TODO Ugly hack cover 80% corner cases, think about how to port sql_query.ts+scanner.ts to Golang, or try to figure out howto tricksterproxy.io parse SQL query to detect timeRange */
```
Comment (bmanth60) [inline pkg/query.go:18]: @Slach additionally, the backend can consume a url, such that instead of building a frontend and backend query, the frontend could forward the query into the backend to handle all of the query processing and return a frontend friendly result.

Comment (Slach) [reply pkg/query.go:18]: we change SQL queries too often in query editor, I think it will request storm

only one thing we need is detect to where is $from and $to macros contains in `formattedQuery` present in `rawQuery` and try to replace it for actual values

or try parse `rawQuery` to detect which tokens are timestamps and replace it
